name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      user_name: 'github-actions[bot]'
      user_email: 'github-actions[bot]@users.noreply.github.com'
      repository: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          check-latest: true
      - run: git config --global user.name $user_name
      - run: git config --global user.email $user_email
      - run: git remote set-url origin https://${{ env.ACTIONS_DEPLOY_ACCESS_TOKEN }}@github.com/${repository}
      - run: rm -rf node_modules/
      - run: npm install
      - run: npm run build
      - run: npm run deploy
